name: Remote SSH
on: [push]
jobs:

  pull:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 129.151.250.191
        username: opc
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          whoami
          cd Tamiyo-s-Library
          git pull

